### ISSUE TITLE
Compatibility flag for INI files using comma as decimal separator

### ISSUE THREAD

**Issue by Sainan** [calamity-inc/iniparser#2]

**Comment by hexarobi** [comment]
Started a PR to try and address this https://github.com/calamity-inc/iniparser/pull/3/files

This works for my needs, but it doesn't yet have a flag to turn it off by default, it's just always on. Still thinking about how best to do the flag if you have any ideas.

**Comment by Sainan** [comment]
This feature will be added in 0.2.11 as it is now on main: 5f8bcdccd1021de8dcb55a4242d5fb5228f5a056
